<definitions name="ConsultarPersonasService"
             targetNamespace="http://localhost:8888/consultar_con_soap"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://localhost:8888/consultar_con_soap"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="ConsultarPersonasRequest"/>

    <message name="Persona">
        <part name="id" type="xsd:int"/>
        <part name="apellidos" type="xsd:string"/>
        <part name="nombres" type="xsd:string"/>
        <part name="dni" type="xsd:int"/>
    </message>

    <message name="ConsultarPersonasResponse">
        <part name="personas" type="tns:Persona" maxOccurs="unbounded"/>
    </message>

    <portType name="ConsultarPersonasPortType">
        <operation name="consultarPersonas">
            <input message="tns:ConsultarPersonasRequest"/>
            <output message="tns:ConsultarPersonasResponse"/>
        </operation>
    </portType>

    <binding name="ConsultarPersonasBinding" type="tns:ConsultarPersonasPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="consultarPersonas">
            <soap:operation soapAction="urn:consultarPersonas"/>
            <input>
                <soap:body use="encoded" namespace="urn:consultarPersonas" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded" namespace="urn:consultarPersonas" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="ConsultarPersonasService">
        <port name="ConsultarPersonasPort" binding="tns:ConsultarPersonasBinding">
            <soap:address location="http://localhost:8888/consultar_con_soap"/>
        </port>
    </service>

</definitions>
